yarnPath: .yarn/releases/yarn-3.2.1.cjs

nodeLinker: node-modules

enableGlobalCache: true

packageExtensions:
  react-native-codegen@*:
    dependencies:
      "@babel/core": ^7
      "@babel/preset-env": ^7

logFilters:
  - level: discard
    pattern: doesn't provide @babel/runtime * requested by @shopify/flash-list
  - level: discard
    pattern: doesn't provide @babel/runtime * requested by @shopify/react-native-performance
