require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../get_react_native_config'

platform :ios, '14.0'

inhibit_all_warnings!
use_frameworks! :linkage => :static

$static_framework = ['CocoaAsyncSocket', 'Flipper', 'Flipper-Boost-iOSX', 'Flipper-DoubleConversion', 'Flipper-Fmt', 'Flipper-Folly', 'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'FlipperKit', 'OpenSSL-Universal', 'SocketRocket', 'YogaKit']

$flipper_configurations = [
 'Debug',
 'Release'
]

target 'RNPrebuild' do
  native_modules_config = get_react_native_config!({
    'react-native-flipper': {
      'configurations': $flipper_configurations
    }
  })
  config = use_native_modules!(native_modules_config)


  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  use_flipper!({
    'Flipper' => '0.166.0', # should match the version of your Flipper client app
    'Flipper-Glog' => '0.5.0.5',
    'Flipper-DoubleConversion' => '3.2.0.1'
    }
  )
end

post_install do |installer|
  # For ReactNative
  react_native_post_install(installer)

  flipper_post_install(installer)

  # Project EXCLUDED_ARCHS build settings 설정
  projects = installer.aggregate_targets
                      .map{ |t| t.user_project }
                      .uniq{ |p| p.path }
                      .push(installer.pods_project)

  projects.each do |project|
    project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386"
      config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
      config.build_settings["SWIFT_SUPPRESS_WARNINGS"] = "YES"
    end
    project.save()
  end

  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
       def pod.build_type
           Pod::BuildType.static_library
       end
    end
  end

  # Sub-Pods Project 설정
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Exclude arm64 from simulator (Apple Silicon)
      # https://stackoverflow.com/a/63955114
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386"

      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
      config.build_settings["SWIFT_SUPPRESS_WARNINGS"] = "YES"
      config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -w -Xanalyzer -analyzer-disable-all-checks"
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = "YES"
      if config.name =~ /Playground/
        # Playground support workaround
        # https://github.com/SnapKit/SnapKit/issues/442#issuecomment-401631932
        config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
      end
    end

    if target.name == 'RCT-Folly'
      target.build_configurations.each do |config|
        config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
      end
    end
    
    # `ReactNativeSpec`의 `Build Phase`에서 `[CP-User] Generate Specs` 설정을 맨 위로 올려, 빌드가 정상적으로 동작하도록 합니다.
    if (target.name&.eql?('FBReactNativeSpec'))
      target.build_phases.each do |build_phase|
        if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
          target.build_phases.move(build_phase, 0)
        end
      end
    end

    # Fix bundle targets requires a development team.
    # https://github.com/CocoaPods/CocoaPods/issues/8891'
    # https://tossteam.slack.com/archives/C02SL8YJGBC/p1645461153068939
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end

  # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
  # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
  # https://github.com/facebook/flipper/issues/834
  #
  # 위에 기술된 버그를 방지하기 위해, 해당 파일에 조건을 절대 만족 할 수 없도록 min ver + 1 로 설정. (현재 최소 13 => 14로 설정)
  `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_14_0/' Pods/RCT-Folly/folly/portability/Time.h`
end
